import { useState } from 'react'
import { FormProvider, useForm } from 'react-hook-form'
import { ArrowLeft, ArrowRight, Briefcase, Check, CheckCircle2, Home, Landmark, Loader2, MapPin, Users, Wallet } from 'lucide-react'

const steps = [{ label: 'Hudud', icon: MapPin }, { label: 'Format', icon: Briefcase }, { label: "Mablag'", icon: Wallet }, { label: 'Kredit', icon: Landmark }, { label: 'Xodimlar', icon: Users }, { label: 'Ijara & Soliq', icon: Home }]
const regions = [['Xorazm', 'Urganch va tumanlar'], ['Toshkent', 'Shahar va viloyat'], ['Samarqand', 'Turizm va savdo'], ['Buxoro', 'Xizmat va savdo'], ["Farg'ona", 'Vodiy bozori'], ['Andijon', 'Ishlab chiqarish'], ['Namangan', 'Savdo va xizmat'], ["Qoraqalpog'iston", 'Hududiy biznes']]
const businesses = [['Restoran', '🍽️', 'Umumiy ovqatlanish'], ['Yetkazib berish', '🚚', 'Logistika xizmati'], ['Savdo', '🛍️', 'Chakana savdo'], ['Ishlab chiqarish', '🏭', 'Mahsulot ishlab chiqarish']]
const defaults = { region: 'Xorazm', business_type: 'Restoran', own_capital: 100000000, need_credit: true, requested_loan_amount: 50000000, loan_term_months: 24, employees_count: 3, average_salary_per_employee: 3000000, monthly_rent: 8000000, entity_type: 'yatt' }
const money = value => `${Number(value || 0).toLocaleString('uz-UZ')} so'm`

function StepHeader({ icon: Icon, title, desc }) { return <header className="step-header"><span><Icon size={23} /></span><div><h1>{title}</h1><p>{desc}</p></div></header> }
function QuickButtons({ values, active, onPick, suffix = 'mln' }) { return <div className="quick-buttons">{values.map(value => <button type="button" key={value} onClick={() => onPick(value)} className={active === value ? 'selected' : ''}>{suffix === 'mln' ? `${value / 1000000} mln` : `${value} ${suffix}`}</button>)}</div> }

function StepBody({ step, methods }) {
  const { watch, setValue } = methods
  const values = watch()
  if (step === 0) return <><StepHeader icon={MapPin} title="Hududni tanlang" desc="Biznesingiz qaysi viloyatda joylashgan?" /><div className="reference-choice-grid">{regions.map(([name, desc]) => <button type="button" key={name} onClick={() => setValue('region', name)} className={values.region === name ? 'selected' : ''}><span className="choice-icon"><MapPin size={20} /></span><span><b>{name}</b><small>{desc}</small></span>{values.region === name && <CheckCircle2 className="check" size={20} />}</button>)}</div></>
  if (step === 1) return <><StepHeader icon={Briefcase} title="Biznes formatini tanlang" desc="Biznesingiz qaysi sohaga tegishli?" /><div className="reference-choice-grid">{businesses.map(([name, emoji, desc]) => <button type="button" key={name} onClick={() => setValue('business_type', name)} className={values.business_type === name ? 'selected' : ''}><span className="business-emoji">{emoji}</span><span><b>{name}</b><small>{desc}</small></span>{values.business_type === name && <CheckCircle2 className="check" size={20} />}</button>)}</div></>
  if (step === 2) return <><StepHeader icon={Wallet} title="O'z mablag'ingiz" desc="Biznesga qancha shaxsiy mablag' kiritasiz?" /><div className="capital-display"><span>Jami o'z mablag'i</span><b>{money(values.own_capital)}</b></div><input className="finance-range" type="range" min="10000000" max="1000000000" step="10000000" value={values.own_capital} onChange={event => setValue('own_capital', Number(event.target.value))} /><QuickButtons values={[50000000, 100000000, 200000000, 500000000]} active={values.own_capital} onPick={value => setValue('own_capital', value)} /><label className="input-label">Yoki aniq summani kiriting<input type="number" min="1" step="5000000" value={values.own_capital} onChange={event => setValue('own_capital', Math.max(0, Number(event.target.value)))} /></label></>
  if (step === 3) return <><StepHeader icon={Landmark} title="Kredit talabi" desc="Bank kreditiga muhtojmisiz?" /><div className="loan-switch"><div><b>Kredit kerakmi?</b><small>Bank moliyalashtirishini so'rash</small></div><button type="button" aria-label="Kredit kerakmi" className={values.need_credit ? 'on' : ''} onClick={() => { setValue('need_credit', !values.need_credit); setValue('requested_loan_amount', values.need_credit ? 0 : 50000000) }}><i /></button></div>{values.need_credit && <div className="loan-details"><div className="range-row"><label>Kredit summasi</label><b>{money(values.requested_loan_amount)}</b></div><input className="finance-range" type="range" min="10000000" max="500000000" step="5000000" value={values.requested_loan_amount} onChange={event => setValue('requested_loan_amount', Number(event.target.value))} /><label className="input-label">Muddat (oy)</label><QuickButtons values={[12, 24, 36]} active={values.loan_term_months} suffix="oy" onPick={value => setValue('loan_term_months', value)} /></div>}</>
  if (step === 4) return <><StepHeader icon={Users} title="Xodimlar va maosh" desc="Nechta xodim ishlaydi va o'rtacha maosh qancha?" /><label className="input-label">Xodimlar soni</label><div className="counter"><button type="button" onClick={() => setValue('employees_count', Math.max(1, values.employees_count - 1))}>−</button><input type="number" min="1" value={values.employees_count} onChange={event => setValue('employees_count', Math.max(1, Number(event.target.value)))} /><button type="button" onClick={() => setValue('employees_count', values.employees_count + 1)}>+</button></div><label className="input-label">O'rtacha oylik maosh (so'm)<input type="number" min="0" step="500000" value={values.average_salary_per_employee} onChange={event => setValue('average_salary_per_employee', Math.max(0, Number(event.target.value)))} /></label><QuickButtons values={[3000000, 5000000, 8000000, 10000000]} active={values.average_salary_per_employee} onPick={value => setValue('average_salary_per_employee', value)} /><div className="soft-summary"><span>Oylik maoshlar jami:</span><b>{money(values.employees_count * values.average_salary_per_employee)}</b></div></>
  return <><StepHeader icon={Home} title="Ijara va soliq turi" desc="Oylik ijara va yuridik shaklingizni tanlang." /><label className="input-label">Oylik ijara to'lovi (so'm)<input type="number" min="0" step="500000" value={values.monthly_rent} onChange={event => setValue('monthly_rent', Math.max(0, Number(event.target.value)))} /></label><QuickButtons values={[0, 5000000, 8000000, 15000000]} active={values.monthly_rent} onPick={value => setValue('monthly_rent', value)} /><label className="input-label">Yuridik shakl va soliq rejimi</label><div className="entity-list">{[['yatt', 'YaTT', "1% aylanma solig'i — 2026 yangi qoida"], ['mchj', 'MChJ', "4% aylanma solig'i"]].map(([id, title, text]) => <button type="button" key={id} onClick={() => setValue('entity_type', id)} className={values.entity_type === id ? 'selected' : ''}><i /><span><b>{title}</b><small>{text}</small></span></button>)}</div></>
}

export default function BusinessWizard({ onSubmit, onReady, busy = false, ready = false, variantName = '', wizardTitle = 'Biznes-reja yaratish', submitLabel = "Hisoblash va Rejani ko'rish" }) {
  const methods = useForm({ defaultValues: defaults })
  const [step, setStep] = useState(0)
  const { handleSubmit, watch } = methods
  const values = watch()
  const valid = step === 0 ? values.region : step === 1 ? values.business_type : step === 2 ? values.own_capital > 0 : step === 3 ? !values.need_credit || values.requested_loan_amount > 0 : step === 4 ? values.employees_count > 0 && values.average_salary_per_employee > 0 : values.monthly_rent >= 0
  const finish = handleSubmit(data => { if (onReady) onReady(data); else onSubmit(data) })
  const label = onReady ? (ready ? `G'oya ${variantName} tayyor` : `G'oya ${variantName} ni tayyorlash`) : submitLabel
  return <FormProvider {...methods}><form className="reference-wizard" onSubmit={event => event.preventDefault()}><header className="wizard-title"><div><h2>{wizardTitle}{variantName ? ` · ${variantName}` : ''}</h2><p>6 qadamda bankka tayyor moliyaviy model tuzing.</p></div><b>{step + 1} / 6</b></header><div className="reference-progress">{steps.map(({ label: stepLabel, icon: Icon }, index) => <div className={index < step ? 'done' : index === step ? 'active' : ''} key={stepLabel}><span>{index < step ? <Check size={15} /> : <Icon size={15} />}</span><small>{stepLabel}</small></div>)}</div><section key={step} className="reference-card animate-scale"><StepBody step={step} methods={methods} /></section><footer className="wizard-nav"><button type="button" className="button ghost" onClick={() => setStep(Math.max(0, step - 1))}><ArrowLeft size={17} />{step === 0 ? 'Bosh sahifa' : 'Orqaga'}</button>{step < 5 ? <button type="button" className="button primary" disabled={!valid} onClick={() => setStep(step + 1)}>Keyingisi<ArrowRight size={17} /></button> : <button type="button" className="button primary" disabled={!valid || busy} onClick={finish}>{busy ? <><Loader2 className="spin" size={17} />Hisoblanmoqda...</> : <>{label}<ArrowRight size={17} /></>}</button>}</footer></form></FormProvider>
}
