import { Link } from 'react-router-dom'

const money = value => `${Number(value || 0).toLocaleString('uz-UZ')} so'm`
const snapshot = result => {
  const financials = result?.financials || {}; const bep = financials.break_even || {}; const opex = financials.opex_monthly || {}; const assumptions = financials.assumptions || {}; const tax = financials.tax_analysis || {}
  const revenue = Math.round((bep.monthly_break_even_revenue || 0) * (assumptions.planning_revenue_multiplier || 1))
  return { bep: bep.monthly_break_even_revenue || 0, score: financials.bank_readiness?.score || 0, regime: tax.selected_regime || 'Noma’lum', tax: tax.estimated_monthly_tax || 0, profit: revenue - (opex.total_fixed_opex || 0), summary: result?.ai_analysis?.executive_summary || 'Tahlil mavjud emas.', swot: result?.ai_analysis?.swot || {} }
}
const better = (a, b, lower = false) => a === b ? 'tie' : (lower ? a < b : a > b) ? 'A' : 'B'
function CompareSide({ name, value, isBetter, format, detail }) { return <div className={`compare-side ${isBetter ? 'is-better' : ''}`}><small>G‘oya {name}</small><strong>{format(value)}</strong>{detail && <em>{detail}</em>}{isBetter && <span className="compare-better">✓ Yaxshiroq</span>}</div> }

export default function CompareResults({ results }) {
  const a = snapshot(results.A), b = snapshot(results.B)
  const metrics = [['BEP', a.bep, b.bep, true, money], ['Bank Readiness Score', a.score, b.score, false, value => `${value}/100`], ['Oylik sof foyda', a.profit, b.profit, false, money]]
  const taxWinner = better(a.tax, b.tax, true)
  return <main className="compare-page"><header className="compare-header"><div><Link className="back-link" to="/compare">← G‘oyalarni tahrirlash</Link><h1>G‘oyalarni solishtirish natijasi</h1><p>Har ikki biznes g‘oyasi bir xil moliyaviy model orqali hisoblandi.</p></div><Link className="button gold" to="/compare">Yangi taqqoslash</Link></header><section className="compare-results-panel"><div className="compare-metrics-grid">{metrics.map(([title, valueA, valueB, lower, format]) => { const result = better(valueA, valueB, lower); return <article className="compare-metric-card" key={title}><div className="compare-metric-header"><h3>{title}</h3><span className={result === 'tie' ? 'neutral' : 'winner'}>{result === 'tie' ? '≈ Teng' : `✓ G‘oya ${result}`}</span></div>{title === 'BEP' && <p className="metric-explainer"><b>BEP — zararsizlik nuqtasi.</b> Bu biznes bir oyda foyda ham, zarar ham qilmasdan barcha doimiy xarajatlarini qoplay olishi uchun zarur bo‘lgan eng kam tushumdir. BEP qancha past bo‘lsa, biznes kamroq savdo bilan xarajatlarini qoplaydi va g‘oya xavfi nisbatan pastroq bo‘ladi.</p>}<div className="compare-metric-columns"><CompareSide name="A" value={valueA} format={format} isBetter={result === 'A'} /><CompareSide name="B" value={valueB} format={format} isBetter={result === 'B'} /></div></article> })}</div><article className="compare-metric-card compare-tax-card"><div className="compare-metric-header"><h3>Tavsiya etilgan soliq rejimi</h3><span className={taxWinner === 'tie' ? 'neutral' : 'winner'}>{taxWinner === 'tie' ? '≈ Teng' : `✓ G‘oya ${taxWinner}`}</span></div><div className="compare-metric-columns"><CompareSide name="A" value={a.regime} format={value => value} detail={money(a.tax)} isBetter={taxWinner === 'A'} /><CompareSide name="B" value={b.regime} format={value => value} detail={money(b.tax)} isBetter={taxWinner === 'B'} /></div></article><div className="compare-summary-grid">{[['A', a], ['B', b]].map(([name, idea]) => <article className="compare-summary-card" key={name}><header><h3>G‘oya {name}</h3><span>{results[name]?.request?.business_type}</span></header><div className="compare-summary-block"><h4>Executive Summary</h4><p>{idea.summary}</p></div><div className="compare-summary-block"><h4>SWOT</h4><div className="compare-swot-grid">{Object.entries(idea.swot).map(([type, items]) => <div className={`compare-swot-card ${type}`} key={type}><h5>{type === 'strengths' ? 'Kuchli tomonlar' : type === 'weaknesses' ? 'Zaif tomonlar' : type === 'opportunities' ? 'Imkoniyatlar' : 'Xavflar'}</h5><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></div>)}</div></div></article>)}</div></section></main>
}
